# Generated by Django 5.2.9 on 2025-12-30 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033')], validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2044)])),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Януари'), (2, 'Февруари'), (3, 'Март'), (4, 'Април'), (5, 'Май'), (6, 'Юни'), (7, 'Юли'), (8, 'Август'), (9, 'Септември'), (10, 'Октомври'), (11, 'Ноември'), (12, 'Декември')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('work_days', models.PositiveSmallIntegerField(choices=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(23)])),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_hours', models.PositiveSmallIntegerField()),
                ('sick_days_noi', models.PositiveSmallIntegerField()),
                ('sick_days_firm', models.PositiveSmallIntegerField()),
                ('vacation_used', models.PositiveSmallIntegerField()),
                ('vacation_paid', models.PositiveSmallIntegerField()),
                ('paid_by_bank', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid_by_cash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mobile', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('workshop', models.CharField(choices=[('AN', 'Антон'), ('A', 'Алуминий'), ('G', 'Стъклопакети'), ('P', 'PVC'), ('I', 'Монтажник'), ('L', 'Общ работник')], max_length=20)),
                ('salary', models.IntegerField()),
                ('total_vacation', models.PositiveSmallIntegerField()),
                ('contract', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033')], validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2044)])),
                ('days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('pay_per_day_vacation', models.PositiveSmallIntegerField()),
                ('pay_per_day_sick', models.PositiveSmallIntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='vacations', to='salaries.workers')),
            ],
        ),
    ]
