# Generated by Django 5.2.9 on 2026-01-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
