# Generated by Django 5.2.9 on 2026-01-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_alter_workers_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='total_vacation',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
