# Generated by Django 5.2.9 on 2026-01-08 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0003_alter_workers_total_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='voucher',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacation',
            name='used_days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='workers',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
