# Generated by Django 5.2.9 on 2026-01-11 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0004_month_voucher_vacation_used_days_workers_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033')], validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2044)])),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Януари'), (2, 'Февруари'), (3, 'Март'), (4, 'Април'), (5, 'Май'), (6, 'Юни'), (7, 'Юли'), (8, 'Август'), (9, 'Септември'), (10, 'Октомври'), (11, 'Ноември'), (12, 'Декември')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('work_days', models.PositiveSmallIntegerField(choices=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23')], validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(23)])),
            ],
        ),
        migrations.CreateModel(
            name='WorkerMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('work_hours', models.PositiveSmallIntegerField()),
                ('sick_days_noi', models.PositiveSmallIntegerField()),
                ('sick_days_firm', models.PositiveSmallIntegerField()),
                ('vacation_used', models.PositiveSmallIntegerField()),
                ('vacation_paid', models.PositiveSmallIntegerField()),
                ('paid_by_bank', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid_by_cash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mobile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('voucher', models.SmallIntegerField(default=0)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_month', to='salaries.currentmonth')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker', to='salaries.workers')),
            ],
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
