# Generated by Django 5.2.9 on 2026-01-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0005_currentmonth_workermonth_delete_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentmonth',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
