# Generated by Django 5.2.9 on 2026-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0006_currentmonth_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermonth',
            name='vacation_to_add',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='initial_vacation',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
