# Generated by Django 5.2.9 on 2026-01-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0007_workermonth_vacation_to_add_workers_initial_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermonth',
            name='salary',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workermonth',
            name='vacation_calc',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
