# Generated by Django 3.2.13 on 2026-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0008_workermonth_salary_workermonth_vacation_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='bonus_one',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='bonus_two',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
