# Generated by Django 3.2.13 on 2026-02-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0009_auto_20260209_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermonth',
            name='bonus_one',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workermonth',
            name='bonus_two',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workermonth',
            name='total_salary',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
