# Generated by Django 3.2.13 on 2026-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0010_auto_20260209_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermonth',
            name='total_salary',
        ),
        migrations.RemoveField(
            model_name='workermonth',
            name='vacation_calc',
        ),
        migrations.AlterField(
            model_name='workers',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='workshop',
            field=models.CharField(choices=[('AN', 'Антон'), ('A', 'Алум.'), ('G', 'Стъклоп.'), ('P', 'PVC'), ('I', 'Монт.'), ('L', 'Общ раб.')], max_length=20),
        ),
    ]
