# Generated by Django 3.2.13 on 2026-02-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0011_auto_20260213_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermonth',
            name='vacation_to_add',
        ),
    ]
