# Generated by Django 5.0.4 on 2026-03-23 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0012_remove_workermonth_vacation_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='initial_vacation',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
