# Generated by Django 5.2.9 on 2026-03-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0013_alter_workers_initial_vacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='workshop',
            field=models.CharField(choices=[('ADM', 'Адм.'), ('AN', 'Антон'), ('A', 'Алум.'), ('G', 'Стъклоп.'), ('P', 'PVC 1'), ('P2', 'PVC 2'), ('I', 'Монт.'), ('L', 'Склад'), ('O', 'Външни')], max_length=20),
        ),
    ]
