# Generated by Django 5.2.9 on 2026-03-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0014_alter_workers_workshop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workermonth',
            old_name='bonus_one',
            new_name='bonus_boss',
        ),
        migrations.RenameField(
            model_name='workermonth',
            old_name='bonus_two',
            new_name='bonus_constant',
        ),
        migrations.RenameField(
            model_name='workermonth',
            old_name='salary',
            new_name='bonus_variable',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='bonus_one',
            new_name='bonus_boss',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='bonus_two',
            new_name='bonus_constant',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='salary',
            new_name='bonus_variable',
        ),
    ]
