# Generated by Django 5.2.9 on 2026-03-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0015_rename_bonus_one_workermonth_bonus_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermonth',
            name='bonus_constant',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workermonth',
            name='voucher',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
