# Generated by Django 5.2.9 on 2026-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0016_alter_workermonth_bonus_constant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermonth',
            name='bonus_boss',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workermonth',
            name='bonus_constant',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
