# Generated by Django 5.2.9 on 2026-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0017_alter_workermonth_bonus_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='bonus_variable',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
