# Generated by Django 5.2.9 on 2026-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0018_alter_workers_bonus_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='workshop',
            field=models.CharField(choices=[('ADM', 'Адм.'), ('AN', 'Антон'), ('A', 'Алум.'), ('G', 'Стъклоп.'), ('zN', 'Непал'), ('P', 'PVC 1'), ('P2', 'PVC 2'), ('I', 'Монт.'), ('L', 'Склад'), ('zO', 'Външни')], max_length=20),
        ),
    ]
