# Generated by Django 5.2.9 on 2026-04-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0019_alter_workers_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='bonus_variable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
