# Generated by Django 5.2.9 on 2026-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0020_alter_workers_bonus_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermonth',
            name='bonus_variable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
